package com.example.agents;

import java.util.List;
import java.util.Map;
import com.example.agents.CommonRequirements.VehicleInfo;
import com.example.agents.CommonRequirements.VehicleMake;
import com.example.agents.CommonRequirements.Dealer;

/**
 * Mock vehicle data for GM car selection agent demos.
 * This class provides hardcoded GM vehicle inventory for demonstration purposes.
 */
public class MockVehicleData {
    
    public static final List<VehicleInfo> VEHICLES = List.of(
        new VehicleInfo(
            // Basic identification
            "GM001",
            VehicleMake.CHEVROLET,
            "Silverado 1500",
            2024,
            "LT",
            "Crew Cab Pickup",
            "1GCUYDED1MZ123456",
            // Pricing and classification
            36800,
            "Truck",
            "Pickup",
            // Fuel economy and emissions
            20,
            23,
            11.8,
            267,
            // Engine and performance
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            24.0,
            null,
            // Dimensions and weight
            231.7,
            81.2,
            75.5,
            147.4,
            4945,
            7000,
            2280,
            13300,
            2280,
            3.5,
            // Capacity
            6,
            4,
            71.7,
            // Appearance
            "Summit White",
            "Jet Black",
            // Features and technology
            List.of("Dual Front Airbags", "Side Airbags", "ABS", "Traction Control", "Stability Control"),
            List.of("Apple CarPlay", "Android Auto", "10.2-inch Touchscreen"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            false,
            // Fleet management
            null,
            null,
            null,
            // Telemetry and diagnostics
            null,
            List.of(),
            "OK",
            0.0,
            null,
            // Trip information
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM002",
            VehicleMake.CHEVROLET,
            "Equinox",
            2024,
            "LS",
            "Compact SUV",
            "2GNAXSEV4M6123457",
            28000,
            "SUV",
            "Compact SUV",
            26,
            31,
            8.7,
            196,
            "Turbocharged 4-cylinder",
            1.5,
            175,
            203,
            "Automatic",
            "FWD",
            "Gasoline",
            14.9,
            null,
            183.1,
            72.6,
            65.4,
            107.3,
            3274,
            4464,
            1190,
            1500,
            1190,
            2.2,
            5,
            4,
            63.9,
            "Mosaic Black Metallic",
            "Jet Black",
            List.of("6 Airbags", "Teen Driver", "Safety Alert Seat", "Automatic Emergency Braking"),
            List.of("Wireless Apple CarPlay", "Android Auto", "WiFi Hotspot"),
            false,
            true,
            "6-Speaker",
            "Single-Zone Manual",
            true,
            true,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM003",
            VehicleMake.GMC,
            "Sierra 1500",
            2024,
            "SLE",
            "Crew Cab Pickup",
            "3GTU9BED2MG123458",
            38300,
            "Truck",
            "Pickup",
            21,
            23,
            11.2,
            253,
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            24.0,
            null,
            231.7,
            81.2,
            75.5,
            147.4,
            4969,
            7000,
            2240,
            13000,
            2240,
            3.5,
            6,
            4,
            71.7,
            "Cardinal Red",
            "Dark Ash",
            List.of("ProGrade Trailering System", "HD Rear Vision Camera", "Bed View Camera"),
            List.of("GMC Infotainment", "13.4-inch Touchscreen", "Google Built-In"),
            true,
            true,
            "Premium Audio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM004",
            VehicleMake.CADILLAC,
            "XT5",
            2024,
            "Luxury",
            "Luxury SUV",
            "1GYKNDRS6MZ123459",
            44990,
            "Luxury SUV",
            "Midsize SUV",
            22,
            29,
            9.8,
            221,
            "Turbocharged 4-cylinder",
            2.0,
            237,
            258,
            "Automatic",
            "FWD",
            "Gasoline",
            18.7,
            null,
            193.6,
            75.0,
            66.0,
            112.5,
            3977,
            5449,
            1472,
            3500,
            1472,
            2.5,
            5,
            4,
            30.0,
            "Radiant Silver Metallic",
            "Sahara Beige",
            List.of("Night Vision", "Surround Vision", "Super Cruise"),
            List.of("AKG Studio Audio", "Navigation", "Wireless Charging"),
            true,
            true,
            "AKG Studio 14-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM005",
            VehicleMake.CHEVROLET,
            "Malibu",
            2024,
            "LT",
            "Midsize Sedan",
            "1G1ZD5ST2MF123460",
            25100,
            "Sedan",
            "Midsize",
            29,
            36,
            7.6,
            172,
            "Turbocharged 4-cylinder",
            1.5,
            160,
            184,
            "CVT",
            "FWD",
            "Gasoline",
            15.8,
            null,
            194.2,
            73.0,
            57.6,
            111.4,
            3223,
            4366,
            1143,
            0,
            1143,
            2.0,
            5,
            4,
            15.7,
            "Silver Ice Metallic",
            "Jet Black",
            List.of("10 Airbags", "Teen Driver", "Lane Keep Assist", "Automatic Emergency Braking"),
            List.of("Wireless Apple CarPlay", "8-inch Touchscreen"),
            false,
            true,
            "6-Speaker",
            "Single-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM006",
            VehicleMake.CHEVROLET,
            "Bolt EV",
            2024,
            "2LT",
            "Electric Hatchback",
            "1G1FY6S03M4123461",
            27495,
            "Electric",
            "Hatchback",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            200,
            266,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            259,
            164.0,
            69.5,
            59.1,
            102.4,
            3589,
            4094,
            505,
            0,
            505,
            1.0,
            5,
            4,
            16.6,
            "Bright Blue Metallic",
            "Dark Ash Gray",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Following Distance Indicator"),
            List.of("Energy Assist", "Regen on Demand", "10.2-inch Display"),
            false,
            true,
            "6-Speaker",
            "Automatic Climate Control",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM007",
            VehicleMake.GMC,
            "Yukon",
            2024,
            "SLT",
            "Full-Size SUV",
            "1GKS2CKC2MR123462",
            58700,
            "Full-Size SUV",
            "Large SUV",
            16,
            20,
            14.7,
            332,
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            28.0,
            null,
            210.0,
            81.0,
            76.7,
            120.9,
            5541,
            7500,
            1959,
            8200,
            1959,
            4.0,
            8,
            4,
            25.5,
            "Onyx Black",
            "Jet Black",
            List.of("Air Ride Suspension", "Magnetic Ride Control", "Enhanced Automatic Emergency Braking"),
            List.of("12.6-inch Display", "Rear Seat Entertainment", "Bose Premium Audio"),
            true,
            true,
            "Bose 10-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM008",
            VehicleMake.CADILLAC,
            "CT5",
            2024,
            "Premium Luxury",
            "Luxury Sedan",
            "1G6DT5RK5M0123463",
            38790,
            "Luxury Sedan",
            "Midsize",
            23,
            34,
            8.4,
            190,
            "Turbocharged 4-cylinder",
            2.0,
            237,
            258,
            "Automatic",
            "RWD",
            "Gasoline",
            17.4,
            null,
            193.8,
            74.0,
            57.3,
            116.0,
            3650,
            4839,
            1189,
            0,
            1189,
            2.0,
            5,
            4,
            11.4,
            "Stellar Black Metallic",
            "Jet Black",
            List.of("Super Cruise", "Night Vision", "Enhanced Automatic Parking Assist"),
            List.of("Bose Performance Series", "Navigation", "Wireless Charging"),
            true,
            true,
            "Bose Performance 15-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM009",
            VehicleMake.CHEVROLET,
            "Traverse",
            2024,
            "LT",
            "3-Row SUV",
            "1GNERKKW2MJ123464",
            35700,
            "3-Row SUV",
            "Large SUV",
            18,
            27,
            11.2,
            253,
            "V6",
            3.6,
            310,
            266,
            "Automatic",
            "FWD",
            "Gasoline",
            19.4,
            null,
            204.3,
            78.6,
            70.7,
            120.9,
            4362,
            5730,
            1368,
            5000,
            1368,
            2.5,
            8,
            4,
            23.0,
            "Silver Ice Metallic",
            "Jet Black",
            List.of("7 Airbags", "Rear Seat Reminder", "HD Surround Vision"),
            List.of("WiFi Hotspot", "8-inch Touchscreen", "Apple CarPlay"),
            false,
            true,
            "6-Speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM010",
            VehicleMake.CHEVROLET,
            "Camaro",
            2024,
            "2LT",
            "Sports Car",
            "1G1FD1RS6M0123465",
            27495,
            "Sports Car",
            "Coupe",
            20,
            30,
            9.4,
            213,
            "Turbocharged 4-cylinder",
            2.0,
            275,
            295,
            "Manual",
            "RWD",
            "Gasoline",
            19.0,
            null,
            188.3,
            74.7,
            53.1,
            110.7,
            3354,
            4199,
            845,
            0,
            845,
            1.5,
            4,
            2,
            9.1,
            "Riverside Blue Metallic",
            "Jet Black",
            List.of("8 Airbags", "Rear Park Assist", "Rear Cross Traffic Alert"),
            List.of("Bose Premium Audio", "Wireless Charging", "8-inch Display"),
            false,
            true,
            "Bose 9-speaker",
            "Dual-Zone Automatic",
            true,
            false,
            true,
            false,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet EV #2
        new VehicleInfo(
            "GM011",
            VehicleMake.CHEVROLET,
            "Bolt EUV",
            2024,
            "Premier",
            "Electric Crossover",
            "1G1FZ6S05M4123466",
            29995,
            "Electric",
            "Crossover",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            200,
            266,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            247,
            169.5,
            69.7,
            63.8,
            105.3,
            3659,
            4174,
            514,
            0,
            514,
            1.0,
            5,
            4,
            16.3,
            "Cherry Red Tintcoat",
            "Sky Cool Gray",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Front Pedestrian Braking", "IntelliBeam"),
            List.of("Super Cruise", "Bose Audio", "Wireless Apple CarPlay"),
            true,
            true,
            "Bose 6-speaker",
            "Automatic Climate Control",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet EV #3
        new VehicleInfo(
            "GM012",
            VehicleMake.CHEVROLET,
            "Equinox EV",
            2024,
            "2LT",
            "Electric SUV",
            "1GNEWJGX5M4123467",
            34995,
            "Electric",
            "Compact SUV",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            210,
            242,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            319,
            190.8,
            76.4,
            65.3,
            111.0,
            4250,
            5500,
            1250,
            1500,
            1250,
            2.75,
            5,
            4,
            57.0,
            "Sterling Gray Metallic",
            "Black",
            List.of("Automatic Emergency Braking", "HD Surround Vision", "Blind Zone Steering Assist"),
            List.of("17.7-inch Display", "Google Built-In", "Wireless Phone Charging"),
            true,
            true,
            "Premium Audio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet EV #4
        new VehicleInfo(
            "GM013",
            VehicleMake.CHEVROLET,
            "Blazer EV",
            2024,
            "2LT",
            "Electric SUV",
            "3GNKDHRS1M4123468",
            47595,
            "Electric",
            "Midsize SUV",
            0,
            0,
            0.0,
            0,
            "Dual Electric Motors",
            0.0,
            288,
            333,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            279,
            192.8,
            78.0,
            65.7,
            115.0,
            4850,
            6001,
            1151,
            2000,
            1151,
            3.0,
            5,
            4,
            25.2,
            "Radiant Red Tintcoat",
            "Night Shift Blue",
            List.of("Automatic Emergency Braking", "Reverse Automatic Braking", "HD Surround Vision"),
            List.of("17.7-inch Display", "11-inch Display", "Bose Premium Audio"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet EV #5
        new VehicleInfo(
            "GM014",
            VehicleMake.CHEVROLET,
            "Silverado EV",
            2024,
            "RST",
            "Electric Pickup",
            "1GT49FEY2M4123469",
            96495,
            "Electric",
            "Pickup",
            0,
            0,
            0.0,
            0,
            "Dual Electric Motors",
            0.0,
            664,
            780,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            450,
            232.7,
            81.7,
            77.9,
            145.7,
            6900,
            8500,
            1600,
            10000,
            1600,
            4.25,
            5,
            4,
            120.9,
            "Black",
            "Jet Black",
            List.of("Super Cruise", "Automatic Emergency Braking", "Blind Zone Steering Assist"),
            List.of("17-inch Display", "Multi-Flex Midgate", "PowerBase Charging"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet EV #6
        new VehicleInfo(
            "GM015",
            VehicleMake.CHEVROLET,
            "Equinox EV",
            2024,
            "3LT",
            "Electric SUV",
            "1GNEWJGX7M4123470",
            41900,
            "Electric",
            "Compact SUV",
            0,
            0,
            0.0,
            0,
            "Dual Electric Motors",
            0.0,
            290,
            346,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            285,
            190.8,
            76.4,
            65.3,
            111.0,
            4450,
            5700,
            1250,
            1500,
            1250,
            2.85,
            5,
            4,
            57.0,
            "Riptide Blue Metallic",
            "Sky Cool Gray",
            List.of("Super Cruise", "Automatic Parking Assist", "Enhanced Automatic Emergency Braking"),
            List.of("17.7-inch Display", "Heated Steering Wheel", "Ventilated Seats"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet EV #7
        new VehicleInfo(
            "GM016",
            VehicleMake.CHEVROLET,
            "Blazer EV",
            2024,
            "RS",
            "Electric SUV",
            "3GNKDHRS3M4123471",
            51995,
            "Electric",
            "Midsize SUV",
            0,
            0,
            0.0,
            0,
            "Dual Electric Motors",
            0.0,
            340,
            325,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            324,
            192.8,
            78.0,
            65.7,
            115.0,
            4900,
            6051,
            1151,
            2000,
            1151,
            3.0,
            5,
            4,
            25.2,
            "Fountain Blue",
            "Adrenaline Red",
            List.of("Super Cruise", "Automatic Lane Change", "Traffic Jam Assist"),
            List.of("17.7-inch Display", "11-inch Display", "Panoramic Sunroof"),
            true,
            true,
            "Bose Centerpoint",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #4
        new VehicleInfo(
            "GM017",
            VehicleMake.CHEVROLET,
            "Tahoe",
            2024,
            "LT",
            "Full-Size SUV",
            "1GNSKBKC4M4123472",
            54295,
            "Full-Size SUV",
            "Large SUV",
            15,
            22,
            13.8,
            312,
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            24.0,
            null,
            210.7,
            81.0,
            77.0,
            120.9,
            5490,
            7400,
            1910,
            8400,
            1910,
            3.7,
            8,
            4,
            25.5,
            "Jet Black",
            "Gideon/Very Dark Atmosphere",
            List.of("Automatic Emergency Braking", "Lane Change Alert", "Rear Cross Traffic Alert"),
            List.of("10.2-inch Display", "Wireless Apple CarPlay", "12-speaker Audio"),
            true,
            true,
            "Bose 12-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #5
        new VehicleInfo(
            "GM018",
            VehicleMake.CHEVROLET,
            "Suburban",
            2024,
            "Premier",
            "Full-Size SUV",
            "1GNSKJKC5M4123473",
            76595,
            "Full-Size SUV",
            "Large SUV",
            14,
            19,
            15.7,
            355,
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            30.0,
            null,
            225.2,
            81.0,
            77.9,
            134.1,
            5824,
            7700,
            1876,
            8300,
            1876,
            3.85,
            9,
            4,
            39.3,
            "Empire Beige Metallic",
            "Jet Black",
            List.of("Super Cruise", "HD Surround Vision", "Adaptive Cruise Control"),
            List.of("Premium Audio", "Rear Seat Media", "Navigation"),
            true,
            true,
            "Bose Centerpoint",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #6
        new VehicleInfo(
            "GM019",
            VehicleMake.CHEVROLET,
            "Colorado",
            2024,
            "Z71",
            "Midsize Pickup",
            "1GCGTDEN4M4123474",
            36095,
            "Truck",
            "Pickup",
            20,
            25,
            10.7,
            242,
            "Turbocharged 4-cylinder",
            2.7,
            310,
            430,
            "Automatic",
            "4WD",
            "Gasoline",
            21.2,
            null,
            213.2,
            74.9,
            71.5,
            131.4,
            4750,
            6250,
            1500,
            7700,
            1500,
            3.125,
            5,
            4,
            54.4,
            "Sand Dune Metallic",
            "Jet Black",
            List.of("Automatic Emergency Braking", "Lane Departure Warning", "Hill Descent Control"),
            List.of("11.3-inch Display", "Wireless Charging", "WiFi Hotspot"),
            true,
            true,
            "6-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #7
        new VehicleInfo(
            "GM020",
            VehicleMake.CHEVROLET,
            "Trax",
            2024,
            "1RS",
            "Subcompact SUV",
            "KL79MPSL5M4123475",
            21495,
            "SUV",
            "Subcompact SUV",
            28,
            32,
            8.1,
            183,
            "Turbocharged 3-cylinder",
            1.2,
            137,
            162,
            "Automatic",
            "FWD",
            "Gasoline",
            13.2,
            null,
            175.5,
            69.9,
            65.9,
            103.5,
            3026,
            4094,
            1068,
            0,
            1068,
            2.05,
            5,
            4,
            25.6,
            "Crimson Metallic",
            "Black",
            List.of("10 Airbags", "Automatic Emergency Braking", "Lane Keep Assist"),
            List.of("8-inch Display", "Wireless Apple CarPlay", "WiFi Hotspot"),
            false,
            true,
            "6-speaker",
            "Manual",
            false,
            false,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #8
        new VehicleInfo(
            "GM021",
            VehicleMake.CHEVROLET,
            "Corvette",
            2024,
            "Stingray",
            "Sports Car",
            "1G1Y82D44M5123476",
            68300,
            "Sports Car",
            "Coupe",
            16,
            24,
            12.3,
            278,
            "V8",
            6.2,
            490,
            465,
            "Automatic",
            "RWD",
            "Gasoline",
            18.5,
            null,
            184.6,
            76.1,
            48.6,
            107.2,
            3535,
            4400,
            865,
            0,
            865,
            2.2,
            2,
            2,
            12.6,
            "Torch Red",
            "Adrenaline Red",
            List.of("Performance Traction Management", "Magnetic Ride Control", "Electronic Limited Slip"),
            List.of("Bose Performance Audio", "Performance Data Recorder", "Head-Up Display"),
            true,
            true,
            "Bose Performance 14-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #9
        new VehicleInfo(
            "GM022",
            VehicleMake.CHEVROLET,
            "Silverado 2500HD",
            2024,
            "High Country",
            "Heavy Duty Pickup",
            "1GC4YUEY5M4123477",
            72795,
            "Truck",
            "Heavy Duty Pickup",
            15,
            18,
            15.7,
            355,
            "Turbo-Diesel V8",
            6.6,
            445,
            910,
            "Automatic",
            "4WD",
            "Diesel",
            36.0,
            null,
            250.1,
            81.8,
            78.5,
            158.9,
            7538,
            11350,
            3812,
            18500,
            3812,
            5.675,
            6,
            4,
            89.8,
            "Pearl White Tricoat",
            "Jet Black/Umber",
            List.of("ProGrade Trailering", "Bed View Camera", "Surround Vision"),
            List.of("13.4-inch Display", "Bose Premium", "MultiPro Tailgate"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Chevrolet non-EV #10
        new VehicleInfo(
            "GM023",
            VehicleMake.CHEVROLET,
            "Trailblazer",
            2024,
            "RS",
            "Subcompact SUV",
            "KL79MSSL5M4123478",
            29395,
            "SUV",
            "Subcompact SUV",
            26,
            30,
            8.7,
            196,
            "Turbocharged 3-cylinder",
            1.3,
            155,
            174,
            "CVT",
            "AWD",
            "Gasoline",
            13.2,
            null,
            178.5,
            71.2,
            64.8,
            103.9,
            3323,
            4500,
            1177,
            1000,
            1177,
            2.25,
            5,
            4,
            54.0,
            "Fountain Blue",
            "Jet Black/Sky Cool Gray",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Rear Seat Reminder"),
            List.of("8-inch Display", "Wireless Apple CarPlay", "Remote Start"),
            false,
            true,
            "7-speaker",
            "Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #1
        new VehicleInfo(
            "GM024",
            VehicleMake.GMC,
            "Hummer EV",
            2024,
            "3X",
            "Electric Pickup",
            "1GT40FE85M4123479",
            98845,
            "Electric",
            "Pickup",
            0,
            0,
            0.0,
            0,
            "Tri-Motor Electric",
            0.0,
            1000,
            11500,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            381,
            216.7,
            86.7,
            81.1,
            134.2,
            9063,
            10550,
            1487,
            7500,
            1487,
            5.275,
            5,
            4,
            81.0,
            "Interstellar White",
            "Lunar Horizon",
            List.of("Super Cruise", "UltraVision", "Automatic Emergency Braking"),
            List.of("13.4-inch Display", "12.3-inch Display", "Infinity Roof"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #2
        new VehicleInfo(
            "GM025",
            VehicleMake.GMC,
            "Hummer EV SUV",
            2024,
            "2X",
            "Electric SUV",
            "1GKS0HKC5M4123480",
            79995,
            "Electric",
            "Large SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            625,
            7400,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            303,
            196.8,
            86.5,
            77.8,
            126.7,
            8903,
            10400,
            1497,
            7500,
            1497,
            5.2,
            5,
            4,
            33.7,
            "Void Black",
            "Jet Black",
            List.of("Extract Mode", "CrabWalk", "Automatic Emergency Braking"),
            List.of("13.4-inch Display", "12.3-inch Display", "Removable Sky Panels"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #3
        new VehicleInfo(
            "GM026",
            VehicleMake.GMC,
            "Sierra EV Denali",
            2024,
            "Edition 1",
            "Electric Pickup",
            "1GT42FEY2M4123481",
            99495,
            "Electric",
            "Pickup",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            754,
            785,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            440,
            233.0,
            81.2,
            78.3,
            145.0,
            7400,
            9500,
            1600,
            10000,
            1600,
            4.75,
            5,
            4,
            120.9,
            "Thunderstorm Gray",
            "Alpine Umber",
            List.of("Super Cruise", "Automatic Lane Change", "Night Vision"),
            List.of("16.8-inch Display", "11-inch Display", "AKG Audio"),
            true,
            true,
            "AKG Studio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #4
        new VehicleInfo(
            "GM027",
            VehicleMake.GMC,
            "Terrain EV",
            2025,
            "Denali",
            "Electric SUV",
            "3GKFNHEY5M4123482",
            48995,
            "Electric",
            "Compact SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            300,
            350,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            320,
            185.0,
            74.9,
            65.2,
            108.4,
            4200,
            5400,
            1200,
            2000,
            1200,
            2.7,
            5,
            4,
            59.0,
            "White Frost Tricoat",
            "Jet Black",
            List.of("Automatic Emergency Braking", "Blind Zone Alert", "HD Surround Vision"),
            List.of("15-inch Display", "Google Built-In", "Wireless Charging"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #5
        new VehicleInfo(
            "GM028",
            VehicleMake.GMC,
            "Acadia EV",
            2025,
            "AT4",
            "Electric SUV",
            "1GKKNXLS5M4123483",
            55995,
            "Electric",
            "Midsize SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            365,
            430,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            365,
            193.5,
            77.9,
            67.8,
            112.8,
            4800,
            6200,
            1400,
            3500,
            1400,
            3.1,
            7,
            4,
            28.3,
            "Volcanic Red Tintcoat",
            "Jet Black/Kalahari",
            List.of("AT4 Off-Road Mode", "Hill Descent Control", "Skid Plates"),
            List.of("15-inch Display", "Bose Audio", "Panoramic Sunroof"),
            true,
            true,
            "Bose Premium",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #6
        new VehicleInfo(
            "GM029",
            VehicleMake.GMC,
            "Canyon EV",
            2025,
            "Elevation",
            "Electric Pickup",
            "1GTG6FEY5M4123484",
            52995,
            "Electric",
            "Midsize Pickup",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            390,
            480,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            350,
            213.0,
            74.9,
            72.0,
            131.4,
            5200,
            6700,
            1500,
            8000,
            1500,
            3.35,
            5,
            4,
            61.1,
            "Sterling Metallic",
            "Jet Black",
            List.of("Automatic Emergency Braking", "ProGrade Trailering", "Multi-Pro Tailgate"),
            List.of("11.3-inch Display", "Wireless Apple CarPlay", "Bose Audio"),
            true,
            true,
            "Bose 7-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC EV #7
        new VehicleInfo(
            "GM030",
            VehicleMake.GMC,
            "Yukon EV Denali",
            2025,
            "Ultimate",
            "Electric SUV",
            "1GKS0FKC5M4123485",
            94995,
            "Electric",
            "Full-Size SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            500,
            620,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            400,
            210.0,
            81.0,
            77.0,
            120.9,
            6800,
            8600,
            1800,
            8000,
            1800,
            4.3,
            8,
            4,
            30.0,
            "Hunter Metallic",
            "Teak/Light Shale",
            List.of("Super Cruise", "Magnetic Ride Control", "Air Ride Adaptive Suspension"),
            List.of("16.8-inch Display", "Rear Seat Entertainment", "AKG Studio Reference"),
            true,
            true,
            "AKG Studio Reference",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #2
        new VehicleInfo(
            "GM031",
            VehicleMake.GMC,
            "Terrain",
            2024,
            "SLE",
            "Compact SUV",
            "3GKFNFEY4M4123486",
            29995,
            "SUV",
            "Compact SUV",
            24,
            28,
            9.4,
            212,
            "Turbocharged 4-cylinder",
            1.5,
            175,
            203,
            "Automatic",
            "FWD",
            "Gasoline",
            14.9,
            null,
            182.3,
            72.4,
            65.2,
            107.3,
            3449,
            4724,
            1275,
            1500,
            1275,
            2.36,
            5,
            4,
            63.7,
            "Summit White",
            "Jet Black",
            List.of("Automatic Emergency Braking", "IntelliBeam", "StabiliTrak"),
            List.of("8-inch Display", "Wireless Apple CarPlay", "WiFi Hotspot"),
            false,
            true,
            "6-speaker",
            "Single-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #3
        new VehicleInfo(
            "GM032",
            VehicleMake.GMC,
            "Acadia",
            2024,
            "AT4",
            "Midsize SUV",
            "1GKKNXLS2M4123487",
            43495,
            "SUV",
            "Midsize SUV",
            21,
            28,
            10.2,
            230,
            "Turbocharged 4-cylinder",
            2.0,
            230,
            258,
            "Automatic",
            "AWD",
            "Gasoline",
            19.0,
            null,
            193.6,
            77.5,
            67.3,
            112.8,
            4198,
            5588,
            1390,
            4000,
            1390,
            2.79,
            7,
            4,
            21.7,
            "Ebony Twilight Metallic",
            "Jet Black",
            List.of("AT4 Off-Road Mode", "Hill Descent Control", "Skid Plates"),
            List.of("8-inch Display", "Bose Audio", "Wireless Charging"),
            true,
            true,
            "Bose 8-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #4
        new VehicleInfo(
            "GM033",
            VehicleMake.GMC,
            "Canyon",
            2024,
            "AT4X",
            "Midsize Pickup",
            "1GTG5FEN8M4123488",
            48995,
            "Truck",
            "Pickup",
            18,
            24,
            11.2,
            253,
            "Turbocharged 4-cylinder",
            2.7,
            310,
            430,
            "Automatic",
            "4WD",
            "Gasoline",
            21.0,
            null,
            213.0,
            74.9,
            72.8,
            131.4,
            5122,
            6620,
            1498,
            7700,
            1498,
            3.31,
            5,
            4,
            54.0,
            "Desert Sand",
            "Jet Black/Cobalt Red",
            List.of("Multimatic DSSV Dampers", "Front/Rear Lockers", "33-inch Tires"),
            List.of("11.3-inch Display", "Bose Audio", "Front Camera"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #5
        new VehicleInfo(
            "GM034",
            VehicleMake.GMC,
            "Sierra 2500HD",
            2024,
            "Denali",
            "Heavy Duty Pickup",
            "1GT49VEY8M4123489",
            75995,
            "Truck",
            "Heavy Duty Pickup",
            14,
            18,
            15.7,
            355,
            "Turbo-Diesel V8",
            6.6,
            445,
            910,
            "Automatic",
            "4WD",
            "Diesel",
            36.0,
            null,
            250.2,
            81.2,
            78.9,
            159.0,
            7628,
            11500,
            3872,
            18500,
            3872,
            5.75,
            6,
            4,
            91.0,
            "Titanium Rush Metallic",
            "Jet Black/Kalahari",
            List.of("ProGrade Trailering", "15 Camera Views", "Transparent Trailer View"),
            List.of("13.4-inch Display", "Premium Audio", "Multi-Pro Tailgate"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #6
        new VehicleInfo(
            "GM035",
            VehicleMake.GMC,
            "Yukon XL",
            2024,
            "Denali",
            "Full-Size SUV",
            "1GKS8JKC8M4123490",
            79695,
            "Full-Size SUV",
            "Large SUV",
            14,
            20,
            14.7,
            332,
            "V8",
            6.2,
            420,
            460,
            "Automatic",
            "4WD",
            "Gasoline",
            30.5,
            null,
            225.2,
            81.0,
            77.4,
            134.1,
            5847,
            7900,
            2053,
            8100,
            2053,
            3.95,
            9,
            4,
            41.5,
            "Dark Sky Metallic",
            "Teak/Light Shale",
            List.of("Magnetic Ride Control", "Super Cruise", "Enhanced Automatic Parking"),
            List.of("Rear Seat Media", "AKG Audio", "Power-Retractable Steps"),
            true,
            true,
            "AKG Studio 18-speaker",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #7
        new VehicleInfo(
            "GM036",
            VehicleMake.GMC,
            "Sierra 3500HD",
            2024,
            "AT4",
            "Heavy Duty Pickup",
            "1GT49TEY4M4123491",
            83495,
            "Truck",
            "Heavy Duty Pickup",
            13,
            18,
            16.8,
            379,
            "Turbo-Diesel V8",
            6.6,
            445,
            910,
            "Automatic",
            "4WD",
            "Diesel",
            36.0,
            null,
            265.2,
            81.2,
            79.8,
            172.1,
            8264,
            14000,
            5736,
            36000,
            5736,
            7.0,
            6,
            4,
            98.3,
            "Onyx Black",
            "Jet Black/Kalahari",
            List.of("AT4 Off-Road Performance", "Rancho Shocks", "Skid Plates"),
            List.of("13.4-inch Display", "Head-Up Display", "Bed View Camera"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // GMC non-EV #8
        new VehicleInfo(
            "GM037",
            VehicleMake.GMC,
            "Savana 2500",
            2024,
            "Work Van",
            "Cargo Van",
            "1GTW7AFG6M4123492",
            41295,
            "Van",
            "Cargo Van",
            15,
            20,
            14.7,
            332,
            "V8",
            6.6,
            401,
            464,
            "Automatic",
            "RWD",
            "Gasoline",
            31.0,
            null,
            224.1,
            79.5,
            83.6,
            135.0,
            5291,
            9600,
            4309,
            10000,
            4309,
            4.8,
            2,
            2,
            239.0,
            "Summit White",
            "Medium Pewter",
            List.of("Rear Vision Camera", "StabiliTrak", "Side-Blind Zone Alert"),
            List.of("4.2-inch Display", "Bluetooth", "OnStar"),
            false,
            true,
            "2-speaker",
            "Manual",
            false,
            false,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #1
        new VehicleInfo(
            "GM038",
            VehicleMake.CADILLAC,
            "LYRIQ",
            2024,
            "Luxury",
            "Electric SUV",
            "1GYKNCRS5M4123493",
            57195,
            "Electric",
            "Luxury SUV",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            340,
            325,
            "Single-Speed",
            "RWD",
            "Electric",
            0.0,
            314,
            196.7,
            77.8,
            63.9,
            121.8,
            5223,
            6550,
            1327,
            3500,
            1327,
            3.275,
            5,
            4,
            31.0,
            "Opulent Blue Metallic",
            "Sky Cool Gray",
            List.of("Super Cruise", "Parking Assist", "Enhanced Automatic Emergency Braking"),
            List.of("33-inch LED Display", "AKG Studio", "Augmented Reality Navigation"),
            true,
            true,
            "AKG Studio 19-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #2
        new VehicleInfo(
            "GM039",
            VehicleMake.CADILLAC,
            "LYRIQ",
            2024,
            "Sport",
            "Electric SUV",
            "1GYKNDRS7M4123494",
            61795,
            "Electric",
            "Luxury SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            500,
            450,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            307,
            196.7,
            77.8,
            63.9,
            121.8,
            5456,
            6783,
            1327,
            3500,
            1327,
            3.39,
            5,
            4,
            31.0,
            "Crystal White Tricoat",
            "Noir",
            List.of("Super Cruise", "Night Vision", "Magnetic Ride Control"),
            List.of("33-inch LED Display", "AKG Studio", "Panoramic Fixed Glass Roof"),
            true,
            true,
            "AKG Studio 19-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #3
        new VehicleInfo(
            "GM040",
            VehicleMake.CADILLAC,
            "CELESTIQ",
            2024,
            "Bespoke",
            "Electric Sedan",
            "1G6A15S62M4123495",
            340000,
            "Electric",
            "Ultra-Luxury Sedan",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            600,
            640,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            300,
            217.2,
            83.2,
            57.4,
            126.0,
            6595,
            7496,
            901,
            0,
            901,
            3.75,
            4,
            4,
            11.2,
            "Hand-Painted Custom",
            "Bespoke Interior",
            List.of("Ultra Cruise", "Active Rear Steering", "Magnetic Ride Control 4.0"),
            List.of("55-inch Pillar-to-Pillar Display", "AKG Studio Reference", "Smart Glass Roof"),
            true,
            true,
            "AKG Studio Reference 38-speaker",
            "Five-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #4
        new VehicleInfo(
            "GM041",
            VehicleMake.CADILLAC,
            "OPTIQ",
            2025,
            "Luxury",
            "Electric SUV",
            "1GYKNARS8M4123496",
            52395,
            "Electric",
            "Compact Luxury SUV",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            300,
            315,
            "Single-Speed",
            "RWD",
            "Electric",
            0.0,
            300,
            190.8,
            75.4,
            64.5,
            114.2,
            4600,
            5800,
            1200,
            2000,
            1200,
            2.9,
            5,
            4,
            26.0,
            "Argent Silver Metallic",
            "Whisper Beige",
            List.of("Automatic Emergency Braking", "Blind Zone Alert", "HD Surround Vision"),
            List.of("33-inch Display", "Google Built-In", "Wireless Phone Charging"),
            true,
            true,
            "Premium Audio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #5
        new VehicleInfo(
            "GM042",
            VehicleMake.CADILLAC,
            "ESCALADE IQ",
            2025,
            "Luxury",
            "Electric SUV",
            "1GYFZFR65M4123497",
            129990,
            "Electric",
            "Full-Size Luxury SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            750,
            785,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            450,
            212.2,
            85.4,
            77.5,
            126.2,
            8600,
            10000,
            1400,
            8000,
            1400,
            5.0,
            7,
            4,
            35.0,
            "Black Raven",
            "Vanilla/Jet Black",
            List.of("Super Cruise", "Four-Wheel Steering", "Magnetic Ride Control"),
            List.of("55-inch Display", "Executive Second Row", "AKG Studio Reference"),
            true,
            true,
            "AKG Studio Reference 40-speaker",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #6
        new VehicleInfo(
            "GM043",
            VehicleMake.CADILLAC,
            "VISTIQ",
            2026,
            "Luxury",
            "Electric SUV",
            "1GYKNJRS4M4123498",
            78995,
            "Electric",
            "Three-Row Electric SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            615,
            650,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            390,
            205.0,
            79.5,
            70.5,
            121.0,
            6200,
            7800,
            1600,
            5000,
            1600,
            3.9,
            7,
            4,
            32.0,
            "Stellar Black Metallic",
            "Maple Sugar/Jet Black",
            List.of("Super Cruise", "Night Vision", "Rear Pedestrian Alert"),
            List.of("33-inch Display", "Rear Entertainment", "Panoramic Sunroof"),
            true,
            true,
            "AKG Studio 23-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac EV #7
        new VehicleInfo(
            "GM044",
            VehicleMake.CADILLAC,
            "OPTIQ",
            2025,
            "Sport",
            "Electric SUV",
            "1GYKNBRS2M4123499",
            58995,
            "Electric",
            "Compact Luxury SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            350,
            380,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            280,
            190.8,
            75.4,
            64.5,
            114.2,
            4850,
            6050,
            1200,
            2000,
            1200,
            3.025,
            5,
            4,
            26.0,
            "Wave Metallic",
            "Adrenaline Red",
            List.of("Super Cruise", "Performance Brakes", "Sport Suspension"),
            List.of("33-inch Display", "Performance Data Recorder", "Head-Up Display"),
            true,
            true,
            "AKG Studio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #2
        new VehicleInfo(
            "GM045",
            VehicleMake.CADILLAC,
            "XT4",
            2024,
            "Sport",
            "Compact Luxury SUV",
            "1GYFZDR44M4123500",
            39590,
            "Luxury SUV",
            "Compact SUV",
            24,
            31,
            8.7,
            196,
            "Turbocharged 4-cylinder",
            2.0,
            237,
            258,
            "Automatic",
            "FWD",
            "Gasoline",
            14.0,
            null,
            181.1,
            73.2,
            63.5,
            109.1,
            3655,
            5000,
            1345,
            3500,
            1345,
            2.5,
            5,
            4,
            48.9,
            "Radiant Silver Metallic",
            "Sedona/Jet Black",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Safety Alert Seat"),
            List.of("8-inch Display", "Wireless Apple CarPlay", "Bose Audio"),
            true,
            true,
            "Bose 8-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #3
        new VehicleInfo(
            "GM046",
            VehicleMake.CADILLAC,
            "XT6",
            2024,
            "Premium Luxury",
            "Three-Row SUV",
            "1GYKPDRS1M4123501",
            49990,
            "Luxury SUV",
            "Midsize SUV",
            19,
            26,
            11.2,
            253,
            "V6",
            3.6,
            310,
            271,
            "Automatic",
            "FWD",
            "Gasoline",
            19.0,
            null,
            198.5,
            77.3,
            69.9,
            112.7,
            4690,
            6091,
            1401,
            4000,
            1401,
            3.05,
            7,
            4,
            21.7,
            "Manhattan Noir Metallic",
            "Cirrus/Jet Black",
            List.of("Night Vision", "HD Surround Vision", "Rear Pedestrian Alert"),
            List.of("8-inch Display", "Navigation", "14-speaker Bose"),
            true,
            true,
            "Bose Performance 14-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #4
        new VehicleInfo(
            "GM047",
            VehicleMake.CADILLAC,
            "Escalade",
            2024,
            "Premium Luxury",
            "Full-Size SUV",
            "1GYS4BKL2M4123502",
            81090,
            "Luxury SUV",
            "Full-Size SUV",
            14,
            19,
            15.7,
            355,
            "V8",
            6.2,
            420,
            460,
            "Automatic",
            "4WD",
            "Gasoline",
            24.0,
            null,
            211.9,
            81.1,
            76.7,
            120.9,
            5655,
            7550,
            1895,
            8200,
            1895,
            3.775,
            7,
            4,
            26.0,
            "Dark Moon Blue Metallic",
            "Brandy/Very Dark Atmosphere",
            List.of("Super Cruise", "Night Vision", "Magnetic Ride Control"),
            List.of("36-speaker AKG Studio", "16.9-inch OLED", "Rear Entertainment"),
            true,
            true,
            "AKG Studio Reference 36-speaker",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #5
        new VehicleInfo(
            "GM048",
            VehicleMake.CADILLAC,
            "CT4",
            2024,
            "Premium Luxury",
            "Compact Sedan",
            "1G6DB5RK1M4123503",
            35590,
            "Luxury Sedan",
            "Compact",
            24,
            34,
            8.4,
            190,
            "Turbocharged 4-cylinder",
            2.0,
            237,
            258,
            "Automatic",
            "RWD",
            "Gasoline",
            13.0,
            null,
            187.2,
            71.4,
            56.0,
            109.3,
            3472,
            4607,
            1135,
            0,
            1135,
            2.3,
            5,
            4,
            10.7,
            "Satin Steel Metallic",
            "Jet Black",
            List.of("Automatic Emergency Braking", "Lane Change Alert", "Safety Alert Seat"),
            List.of("8-inch Display", "Wireless Charging", "Bose Audio"),
            false,
            true,
            "Bose 9-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #6
        new VehicleInfo(
            "GM049",
            VehicleMake.CADILLAC,
            "CT5-V",
            2024,
            "V-Series",
            "Performance Sedan",
            "1G6DV5RK8M4123504",
            52690,
            "Luxury Sedan",
            "Performance",
            18,
            26,
            11.2,
            253,
            "Twin-Turbo V6",
            3.0,
            360,
            405,
            "Automatic",
            "AWD",
            "Gasoline",
            17.4,
            null,
            193.8,
            74.1,
            57.3,
            116.0,
            3982,
            5161,
            1179,
            0,
            1179,
            2.58,
            5,
            4,
            11.4,
            "Electric Blue",
            "Jet Black/Carbon Fiber",
            List.of("Performance Traction Management", "Magnetic Ride Control", "Brembo Brakes"),
            List.of("Performance Data Recorder", "Head-Up Display", "16-speaker AKG"),
            true,
            true,
            "AKG Studio 16-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #7
        new VehicleInfo(
            "GM050",
            VehicleMake.CADILLAC,
            "CT5-V Blackwing",
            2024,
            "Blackwing",
            "Super Sedan",
            "1G6DZ5RG5M4123505",
            92995,
            "Luxury Sedan",
            "Performance",
            13,
            22,
            15.7,
            355,
            "Supercharged V8",
            6.2,
            668,
            659,
            "Manual",
            "RWD",
            "Gasoline",
            18.5,
            null,
            194.9,
            74.1,
            56.5,
            116.0,
            4217,
            5396,
            1179,
            0,
            1179,
            2.7,
            5,
            4,
            11.9,
            "Rift Metallic",
            "Natural Tan/Jet Black",
            List.of("Performance Traction Management", "Magnetic Ride Control 4.0", "Carbon Ceramic Brakes"),
            List.of("Performance Data Recorder", "HUD", "AKG Studio 16-speaker"),
            true,
            true,
            "AKG Studio 16-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Cadillac non-EV #8
        new VehicleInfo(
            "GM051",
            VehicleMake.CADILLAC,
            "Escalade-V",
            2024,
            "V-Series",
            "Performance SUV",
            "1GYS4NKL9M4123506",
            152490,
            "Luxury SUV",
            "Performance SUV",
            11,
            16,
            18.1,
            409,
            "Supercharged V8",
            6.2,
            682,
            653,
            "Automatic",
            "AWD",
            "Gasoline",
            24.0,
            null,
            211.9,
            81.1,
            76.4,
            120.9,
            6217,
            8113,
            1896,
            7100,
            1896,
            4.06,
            7,
            4,
            28.0,
            "Black Raven",
            "Zebrano Wood/Jet Black",
            List.of("Magnetic Ride Control", "Air Ride Adaptive Suspension", "Electronic Limited Slip"),
            List.of("36-speaker AKG", "16.9-inch OLED", "Augmented Reality Navigation"),
            true,
            true,
            "AKG Studio Reference 36-speaker",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #1
        new VehicleInfo(
            "GM052",
            VehicleMake.BUICK,
            "Electra E4",
            2025,
            "Essence",
            "Electric SUV",
            "KL4MMDSL5M4123507",
            50000,
            "Electric",
            "Compact SUV",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            280,
            290,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            300,
            192.3,
            75.8,
            63.8,
            114.2,
            4600,
            5800,
            1200,
            2000,
            1200,
            2.9,
            5,
            4,
            23.0,
            "White Frost Tricoat",
            "Whisper Beige",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Adaptive Cruise Control"),
            List.of("30-inch Display", "Google Built-In", "QuietTuning"),
            true,
            true,
            "Premium Audio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #2
        new VehicleInfo(
            "GM053",
            VehicleMake.BUICK,
            "Electra E5",
            2025,
            "Avenir",
            "Electric SUV",
            "KL4NNESL8M4123508",
            65000,
            "Electric",
            "Midsize SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            340,
            380,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            320,
            197.7,
            77.5,
            65.5,
            118.4,
            5100,
            6400,
            1300,
            3500,
            1300,
            3.2,
            7,
            4,
            29.0,
            "Sapphire Metallic",
            "Chestnut/Ebony",
            List.of("Super Cruise", "Night Vision", "HD Surround Vision"),
            List.of("30-inch OLED Display", "Bose Premium", "Panoramic Sunroof"),
            true,
            true,
            "Bose Premium 12-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #3
        new VehicleInfo(
            "GM054",
            VehicleMake.BUICK,
            "Wildcat EV",
            2025,
            "Concept",
            "Electric Coupe",
            "KL4PPFSL2M4123509",
            75000,
            "Electric",
            "Luxury Coupe",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            400,
            450,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            350,
            195.0,
            78.0,
            56.0,
            115.0,
            4800,
            6000,
            1200,
            0,
            1200,
            3.0,
            4,
            2,
            10.0,
            "Electric Blue Metallic",
            "Moonlight/Electric Blue",
            List.of("Advanced Driver Assistance", "Predictive Suspension", "360-degree Camera"),
            List.of("Holographic Display", "Spatial Audio", "Biometric Entry"),
            true,
            true,
            "Spatial Audio System",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #4
        new VehicleInfo(
            "GM055",
            VehicleMake.BUICK,
            "Electra GS",
            2025,
            "Sport",
            "Electric SUV",
            "KL4QQGSL5M4123510",
            58000,
            "Electric",
            "Sport SUV",
            0,
            0,
            0.0,
            0,
            "Dual Motor Electric",
            0.0,
            380,
            420,
            "Single-Speed",
            "AWD",
            "Electric",
            0.0,
            290,
            192.3,
            75.8,
            63.0,
            114.2,
            4900,
            6200,
            1300,
            2500,
            1300,
            3.1,
            5,
            4,
            23.0,
            "Sport Red Metallic",
            "Jet Black/Red Accents",
            List.of("Sport Mode Plus", "Performance Brakes", "Adaptive Suspension"),
            List.of("Performance Display", "Sport Sound Enhancement", "Track Apps"),
            true,
            true,
            "Performance Audio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #5
        new VehicleInfo(
            "GM056",
            VehicleMake.BUICK,
            "Envision EV",
            2025,
            "Preferred",
            "Electric SUV",
            "LRBFZLR55M4123511",
            42000,
            "Electric",
            "Compact SUV",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            250,
            280,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            280,
            187.4,
            75.5,
            65.9,
            109.0,
            4400,
            5600,
            1200,
            1500,
            1200,
            2.8,
            5,
            4,
            25.3,
            "Summit White",
            "Shale/Jet Black",
            List.of("Automatic Emergency Braking", "Blind Zone Alert", "Rear Cross Traffic Alert"),
            List.of("10.2-inch Display", "Wireless Apple CarPlay", "Buick Connect"),
            false,
            true,
            "7-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #6
        new VehicleInfo(
            "GM057",
            VehicleMake.BUICK,
            "Encore EV",
            2025,
            "Select",
            "Electric Crossover",
            "KL4AACSL2M4123512",
            35000,
            "Electric",
            "Subcompact SUV",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            200,
            240,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            250,
            181.5,
            73.5,
            64.1,
            105.7,
            3800,
            5000,
            1200,
            1000,
            1200,
            2.5,
            5,
            4,
            23.7,
            "Moonstone Gray Metallic",
            "Ebony",
            List.of("Forward Collision Alert", "Lane Departure Warning", "Teen Driver"),
            List.of("8-inch Display", "Apple CarPlay", "4G LTE WiFi"),
            false,
            true,
            "6-speaker",
            "Single-Zone Automatic",
            false,
            false,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick EV #7
        new VehicleInfo(
            "GM058",
            VehicleMake.BUICK,
            "Century EV",
            2025,
            "Luxury",
            "Electric Sedan",
            "LSGKZ54L5M4123513",
            70000,
            "Electric",
            "Full-Size Sedan",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            300,
            330,
            "Single-Speed",
            "RWD",
            "Electric",
            0.0,
            310,
            206.8,
            76.4,
            59.6,
            120.9,
            5200,
            6500,
            1300,
            0,
            1300,
            3.25,
            5,
            4,
            17.2,
            "Crystal White Pearl",
            "Cognac/Black",
            List.of("Adaptive Air Suspension", "Matrix LED Headlights", "Level 2+ Autonomy"),
            List.of("Curved OLED Display", "Executive Rear Seats", "Champagne Cooler"),
            true,
            true,
            "Bose Panaray 18-speaker",
            "Quad-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #1
        new VehicleInfo(
            "GM059",
            VehicleMake.BUICK,
            "Envista",
            2024,
            "Preferred",
            "Subcompact SUV",
            "KL4CJASB5M4123514",
            23495,
            "SUV",
            "Subcompact SUV",
            30,
            32,
            7.8,
            176,
            "Turbocharged 3-cylinder",
            1.2,
            136,
            148,
            "CVT",
            "FWD",
            "Gasoline",
            13.6,
            null,
            179.1,
            71.8,
            64.0,
            104.9,
            2913,
            3964,
            1051,
            0,
            1051,
            1.98,
            5,
            4,
            42.0,
            "Sapphire Metallic",
            "Black/Blue Accents",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Following Distance Indicator"),
            List.of("8-inch Display", "Wireless Apple CarPlay", "QuietTuning"),
            false,
            true,
            "6-speaker",
            "Automatic",
            false,
            false,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #2
        new VehicleInfo(
            "GM060",
            VehicleMake.BUICK,
            "Encore GX",
            2024,
            "Select",
            "Subcompact SUV",
            "KL4MMBSB1M4123515",
            26195,
            "SUV",
            "Subcompact SUV",
            29,
            32,
            8.1,
            183,
            "Turbocharged 3-cylinder",
            1.2,
            137,
            162,
            "CVT",
            "FWD",
            "Gasoline",
            13.2,
            null,
            175.5,
            71.4,
            65.9,
            102.2,
            3070,
            4190,
            1120,
            0,
            1120,
            2.1,
            5,
            4,
            50.2,
            "Summit White",
            "Ebony",
            List.of("Automatic Emergency Braking", "IntelliBeam", "Front Pedestrian Braking"),
            List.of("8-inch Display", "WiFi Hotspot", "Buick Infotainment"),
            false,
            true,
            "6-speaker",
            "Single-Zone Automatic",
            false,
            false,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #3
        new VehicleInfo(
            "GM061",
            VehicleMake.BUICK,
            "Envision",
            2024,
            "Essence",
            "Compact SUV",
            "LRBFZAR41M4123516",
            35295,
            "SUV",
            "Compact SUV",
            24,
            31,
            8.7,
            196,
            "Turbocharged 4-cylinder",
            2.0,
            228,
            258,
            "Automatic",
            "FWD",
            "Gasoline",
            15.9,
            null,
            183.7,
            75.5,
            65.5,
            107.9,
            3755,
            5070,
            1315,
            1500,
            1315,
            2.535,
            5,
            4,
            47.1,
            "Cinnabar Metallic",
            "Whisper Beige",
            List.of("HD Surround Vision", "Adaptive Cruise Control", "Enhanced Automatic Parking"),
            List.of("10.2-inch Display", "Navigation", "Bose Premium Audio"),
            true,
            true,
            "Bose 7-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #4
        new VehicleInfo(
            "GM062",
            VehicleMake.BUICK,
            "Enclave",
            2024,
            "Avenir",
            "Three-Row SUV",
            "5GAEVCKW4M4123517",
            58195,
            "SUV",
            "Large SUV",
            17,
            25,
            11.8,
            267,
            "V6",
            3.6,
            310,
            266,
            "Automatic",
            "AWD",
            "Gasoline",
            19.0,
            null,
            204.8,
            78.8,
            71.7,
            120.9,
            4755,
            6195,
            1440,
            5000,
            1440,
            3.1,
            7,
            4,
            23.8,
            "White Frost Tricoat",
            "Chestnut/Ebony",
            List.of("Night Vision", "HD Surround Vision", "Rear Pedestrian Alert"),
            List.of("10.2-inch Display", "Rear Entertainment", "Bose Premium"),
            true,
            true,
            "Bose Premium 10-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #5
        new VehicleInfo(
            "GM063",
            VehicleMake.BUICK,
            "LaCrosse",
            2024,
            "Essence",
            "Full-Size Sedan",
            "1G4GA5GR0M4123518",
            42990,
            "Sedan",
            "Full-Size",
            21,
            31,
            9.4,
            212,
            "V6",
            3.6,
            310,
            268,
            "Automatic",
            "FWD",
            "Gasoline",
            15.7,
            null,
            197.5,
            73.5,
            58.4,
            114.4,
            3883,
            5053,
            1170,
            0,
            1170,
            2.53,
            5,
            4,
            15.0,
            "Dark Moon Blue Metallic",
            "Shale/Brownstone",
            List.of("Forward Collision Alert", "Lane Change Alert", "Safety Alert Seat"),
            List.of("8-inch Display", "Wireless Charging", "Bose Audio"),
            true,
            true,
            "Bose 11-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #6
        new VehicleInfo(
            "GM064",
            VehicleMake.BUICK,
            "Regal Sportback",
            2024,
            "GS",
            "Midsize Hatchback",
            "W04GA5SR5M4123519",
            39995,
            "Hatchback",
            "Midsize",
            22,
            32,
            9.0,
            203,
            "Turbocharged 4-cylinder",
            2.0,
            250,
            295,
            "Automatic",
            "AWD",
            "Gasoline",
            14.0,
            null,
            192.2,
            73.6,
            57.5,
            111.4,
            3779,
            4963,
            1184,
            0,
            1184,
            2.48,
            5,
            5,
            31.5,
            "Sport Red Metallic",
            "Ebony",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Adaptive Cruise Control"),
            List.of("8-inch Display", "Navigation", "Bose Premium Audio"),
            true,
            true,
            "Bose 9-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        // Buick non-EV #7
        new VehicleInfo(
            "GM065",
            VehicleMake.BUICK,
            "Envision Plus",
            2024,
            "Avenir",
            "Compact SUV",
            "LRBFZBR48M4123520",
            42495,
            "SUV",
            "Compact SUV",
            22,
            29,
            9.4,
            212,
            "Turbocharged 4-cylinder",
            2.0,
            228,
            258,
            "Automatic",
            "AWD",
            "Gasoline",
            15.9,
            null,
            183.7,
            75.5,
            65.5,
            107.9,
            3942,
            5257,
            1315,
            1500,
            1315,
            2.63,
            5,
            4,
            47.1,
            "Rich Garnet Metallic",
            "Maple Sugar/Ebony",
            List.of("HD Surround Vision", "Night Vision", "Head-Up Display"),
            List.of("10.2-inch Display", "Bose Studio", "Panoramic Moonroof"),
            true,
            true,
            "Bose Studio 10-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        )
    );
    
    public static final List<Dealer> DEALERS = List.of(
        new Dealer("DLR001", "Capitol Chevrolet", "San Jose, CA"),
        new Dealer("DLR002", "Fremont GMC", "Fremont, CA"),
        new Dealer("DLR003", "Stevens Creek Cadillac", "San Jose, CA"),
        new Dealer("DLR004", "Dublin Chevrolet", "Dublin, CA")
    );
    
    public static final Map<String, Double> FINANCING_RATES = Map.of(
        "excellent", 3.9,
        "good", 5.9,
        "fair", 7.9,
        "subprime", 10.9
    );
}