package com.example.agents;

import java.util.List;
import java.util.Map;
import com.example.agents.CommonRequirements.VehicleInfo;
import com.example.agents.CommonRequirements.Dealer;

/**
 * Mock vehicle data for GM car selection agent demos.
 * This class provides hardcoded GM vehicle inventory for demonstration purposes.
 */
public class MockVehicleData {
    
    public static final List<VehicleInfo> VEHICLES = List.of(
        new VehicleInfo(
            // Basic identification
            "GM001",
            "Chevrolet",
            "Silverado 1500",
            2024,
            "LT",
            "Crew Cab Pickup",
            "1GCUYDED1MZ123456",
            // Pricing and classification
            36800,
            "Truck",
            "Pickup",
            // Fuel economy and emissions
            20,
            23,
            11.8,
            267,
            // Engine and performance
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            24.0,
            null,
            // Dimensions and weight
            231.7,
            81.2,
            75.5,
            147.4,
            4945,
            7000,
            2280,
            13300,
            2280,
            3.5,
            // Capacity
            6,
            4,
            71.7,
            // Appearance
            "Summit White",
            "Jet Black",
            // Features and technology
            List.of("Dual Front Airbags", "Side Airbags", "ABS", "Traction Control", "Stability Control"),
            List.of("Apple CarPlay", "Android Auto", "10.2-inch Touchscreen"),
            true,
            true,
            "Bose Premium",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            false,
            // Fleet management
            null,
            null,
            null,
            // Telemetry and diagnostics
            null,
            List.of(),
            "OK",
            0.0,
            null,
            // Trip information
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM002",
            "Chevrolet",
            "Equinox",
            2024,
            "LS",
            "Compact SUV",
            "2GNAXSEV4M6123457",
            28000,
            "SUV",
            "Compact SUV",
            26,
            31,
            8.7,
            196,
            "Turbocharged 4-cylinder",
            1.5,
            175,
            203,
            "Automatic",
            "FWD",
            "Gasoline",
            14.9,
            null,
            183.1,
            72.6,
            65.4,
            107.3,
            3274,
            4464,
            1190,
            1500,
            1190,
            2.2,
            5,
            4,
            63.9,
            "Mosaic Black Metallic",
            "Jet Black",
            List.of("6 Airbags", "Teen Driver", "Safety Alert Seat", "Automatic Emergency Braking"),
            List.of("Wireless Apple CarPlay", "Android Auto", "WiFi Hotspot"),
            false,
            true,
            "6-Speaker",
            "Single-Zone Manual",
            true,
            true,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM003",
            "GMC",
            "Sierra 1500",
            2024,
            "SLE",
            "Crew Cab Pickup",
            "3GTU9BED2MG123458",
            38300,
            "Truck",
            "Pickup",
            21,
            23,
            11.2,
            253,
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            24.0,
            null,
            231.7,
            81.2,
            75.5,
            147.4,
            4969,
            7000,
            2240,
            13000,
            2240,
            3.5,
            6,
            4,
            71.7,
            "Cardinal Red",
            "Dark Ash",
            List.of("ProGrade Trailering System", "HD Rear Vision Camera", "Bed View Camera"),
            List.of("GMC Infotainment", "13.4-inch Touchscreen", "Google Built-In"),
            true,
            true,
            "Premium Audio",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM004",
            "Cadillac",
            "XT5",
            2024,
            "Luxury",
            "Luxury SUV",
            "1GYKNDRS6MZ123459",
            44990,
            "Luxury SUV",
            "Midsize SUV",
            22,
            29,
            9.8,
            221,
            "Turbocharged 4-cylinder",
            2.0,
            237,
            258,
            "Automatic",
            "FWD",
            "Gasoline",
            18.7,
            null,
            193.6,
            75.0,
            66.0,
            112.5,
            3977,
            5449,
            1472,
            3500,
            1472,
            2.5,
            5,
            4,
            30.0,
            "Radiant Silver Metallic",
            "Sahara Beige",
            List.of("Night Vision", "Surround Vision", "Super Cruise"),
            List.of("AKG Studio Audio", "Navigation", "Wireless Charging"),
            true,
            true,
            "AKG Studio 14-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM005",
            "Chevrolet",
            "Malibu",
            2024,
            "LT",
            "Midsize Sedan",
            "1G1ZD5ST2MF123460",
            25100,
            "Sedan",
            "Midsize",
            29,
            36,
            7.6,
            172,
            "Turbocharged 4-cylinder",
            1.5,
            160,
            184,
            "CVT",
            "FWD",
            "Gasoline",
            15.8,
            null,
            194.2,
            73.0,
            57.6,
            111.4,
            3223,
            4366,
            1143,
            0,
            1143,
            2.0,
            5,
            4,
            15.7,
            "Silver Ice Metallic",
            "Jet Black",
            List.of("10 Airbags", "Teen Driver", "Lane Keep Assist", "Automatic Emergency Braking"),
            List.of("Wireless Apple CarPlay", "8-inch Touchscreen"),
            false,
            true,
            "6-Speaker",
            "Single-Zone Automatic",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM006",
            "Chevrolet",
            "Bolt EV",
            2024,
            "2LT",
            "Electric Hatchback",
            "1G1FY6S03M4123461",
            27495,
            "Electric",
            "Hatchback",
            0,
            0,
            0.0,
            0,
            "Electric Motor",
            0.0,
            200,
            266,
            "Single-Speed",
            "FWD",
            "Electric",
            0.0,
            259,
            164.0,
            69.5,
            59.1,
            102.4,
            3589,
            4094,
            505,
            0,
            505,
            1.0,
            5,
            4,
            16.6,
            "Bright Blue Metallic",
            "Dark Ash Gray",
            List.of("Automatic Emergency Braking", "Lane Keep Assist", "Following Distance Indicator"),
            List.of("Energy Assist", "Regen on Demand", "10.2-inch Display"),
            false,
            true,
            "6-Speaker",
            "Automatic Climate Control",
            true,
            true,
            true,
            false,
            true,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM007",
            "GMC",
            "Yukon",
            2024,
            "SLT",
            "Full-Size SUV",
            "1GKS2CKC2MR123462",
            58700,
            "Full-Size SUV",
            "Large SUV",
            16,
            20,
            14.7,
            332,
            "V8",
            5.3,
            355,
            383,
            "Automatic",
            "4WD",
            "Gasoline",
            28.0,
            null,
            210.0,
            81.0,
            76.7,
            120.9,
            5541,
            7500,
            1959,
            8200,
            1959,
            4.0,
            8,
            4,
            25.5,
            "Onyx Black",
            "Jet Black",
            List.of("Air Ride Suspension", "Magnetic Ride Control", "Enhanced Automatic Emergency Braking"),
            List.of("12.6-inch Display", "Rear Seat Entertainment", "Bose Premium Audio"),
            true,
            true,
            "Bose 10-speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            true,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM008",
            "Cadillac",
            "CT5",
            2024,
            "Premium Luxury",
            "Luxury Sedan",
            "1G6DT5RK5M0123463",
            38790,
            "Luxury Sedan",
            "Midsize",
            23,
            34,
            8.4,
            190,
            "Turbocharged 4-cylinder",
            2.0,
            237,
            258,
            "Automatic",
            "RWD",
            "Gasoline",
            17.4,
            null,
            193.8,
            74.0,
            57.3,
            116.0,
            3650,
            4839,
            1189,
            0,
            1189,
            2.0,
            5,
            4,
            11.4,
            "Stellar Black Metallic",
            "Jet Black",
            List.of("Super Cruise", "Night Vision", "Enhanced Automatic Parking Assist"),
            List.of("Bose Performance Series", "Navigation", "Wireless Charging"),
            true,
            true,
            "Bose Performance 15-speaker",
            "Dual-Zone Automatic",
            true,
            true,
            true,
            true,
            true,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM009",
            "Chevrolet",
            "Traverse",
            2024,
            "LT",
            "3-Row SUV",
            "1GNERKKW2MJ123464",
            35700,
            "3-Row SUV",
            "Large SUV",
            18,
            27,
            11.2,
            253,
            "V6",
            3.6,
            310,
            266,
            "Automatic",
            "FWD",
            "Gasoline",
            19.4,
            null,
            204.3,
            78.6,
            70.7,
            120.9,
            4362,
            5730,
            1368,
            5000,
            1368,
            2.5,
            8,
            4,
            23.0,
            "Silver Ice Metallic",
            "Jet Black",
            List.of("7 Airbags", "Rear Seat Reminder", "HD Surround Vision"),
            List.of("WiFi Hotspot", "8-inch Touchscreen", "Apple CarPlay"),
            false,
            true,
            "6-Speaker",
            "Tri-Zone Automatic",
            true,
            true,
            true,
            false,
            false,
            false,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        ),
        new VehicleInfo(
            "GM010",
            "Chevrolet",
            "Camaro",
            2024,
            "2LT",
            "Sports Car",
            "1G1FD1RS6M0123465",
            27495,
            "Sports Car",
            "Coupe",
            20,
            30,
            9.4,
            213,
            "Turbocharged 4-cylinder",
            2.0,
            275,
            295,
            "Manual",
            "RWD",
            "Gasoline",
            19.0,
            null,
            188.3,
            74.7,
            53.1,
            110.7,
            3354,
            4199,
            845,
            0,
            845,
            1.5,
            4,
            2,
            9.1,
            "Riverside Blue Metallic",
            "Jet Black",
            List.of("8 Airbags", "Rear Park Assist", "Rear Cross Traffic Alert"),
            List.of("Bose Premium Audio", "Wireless Charging", "8-inch Display"),
            false,
            true,
            "Bose 9-speaker",
            "Dual-Zone Automatic",
            true,
            false,
            true,
            false,
            false,
            true,
            null,
            null,
            null,
            null,
            List.of(),
            "OK",
            0.0,
            null,
            0.0,
            0.0,
            0.0,
            0.0
        )
    );
    
    public static final List<Dealer> DEALERS = List.of(
        new Dealer("DLR001", "Capitol Chevrolet", "San Jose, CA"),
        new Dealer("DLR002", "Fremont GMC", "Fremont, CA"),
        new Dealer("DLR003", "Stevens Creek Cadillac", "San Jose, CA"),
        new Dealer("DLR004", "Dublin Chevrolet", "Dublin, CA")
    );
    
    public static final Map<String, Double> FINANCING_RATES = Map.of(
        "excellent", 3.9,
        "good", 5.9,
        "fair", 7.9,
        "subprime", 10.9
    );
}